[[main]]
  identifier = 'home'
  name = 'Home'
  url = '/'
  weight = 1
[[main]]
  identifier = 'resume'
  name = 'Résumé'
  url = '/resume/'
  weight = 2
[[main]]
  identifier = 'projects'
  name = 'Projects'
  url = '/projects/'
  weight = 3
