[[main]]
  identifier = 'home'
  name = 'Home'
  url = '/'
  weight = 1
[[main]]
  identifier = 'resume'
  name = 'Resume'
  url = '/resume/'
  weight = 2
[[main]]
  identifier = 'projects'
  name = 'Projects'
  url = '/projects/'
  weight = 3
[[main]]
  identifier = 'unity'
  name = 'Unity'
  url = '/unity/'
  weight = 4
[[main]]
  identifier = 'contact'
  name = 'Contact'
  url = '/contact/'
  weight = 5
